version: '3.4'

x-common-variables: &common-variables
 CELERY_BROKER_URL: redis://redis:6379
 CELERY_RESULT_BACKEND: redis://redis:6379
 MINIO_ACCESS_KEY: minio
 MINIO_SECRET_KEY: minio123
 MINIO_URL: minio:9000
 MINIO_BUCKET_NAME: hse-api-bucket
 MYSQL_HOST: mysql
 MYSQL_ROOT_PASSWORD: mysql123
 MYSQL_USER: mysql
 MYSQL_PASSWORD: mysql123
 MYSQL_DATABASE: hse-api-database
 RESTRICTED_MODE: 0

services:
 annotatrix:
  build: .
  container_name: annotatrix_prod
  ports:
   - "8000:5316"
  links:
   - hse-api-web
  environment: *common-variables


 hse-api-web:
  build: ../hseling-api-universal-dependencies
  container_name: api_for_annotatrix
  ports:
   - "80:80"
  links:
   - redis
   - minio
   - mysql
   - hse-api-celery
  environment: *common-variables

 hse-api-celery:
  build: ../hseling-api-universal-dependencies
  command: celery -A main.celery worker
  links:
   - redis
   - minio
   - mysql
  environment: *common-variables

 minio:
  image: minio/minio:latest
  volumes:
   - data:/data
  ports:
   - "9000:9000"
  command: server /data/minio
  environment: *common-variables

 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: *common-variables

 redis:
  image: redis:latest

volumes:
  data:
